#!/bin/bash

if [[ "" == "$1" || "--help" == "$1" || "-h" == "$1" ]] ; then
    echo "usage: $0 FILE" 1>&2
    echo "where FILE is something like: foo-0.2.3-1-x86_64.pkg.tar.gz"
    exit 1
fi

REPO="ftp://seblu.net/archlinux/arm/packages"
FILENAME=$1
PKGLETTER="$(echo $1 | head -c 1)"
PKGNAME="$(echo $1 | sed -e 's/-[^-]*-[0-9]*-[a-z0-9_]*\.pkg\.tar\.xz//')"
URL="$REPO/${PKGLETTER}/${PKGNAME}/${FILENAME}"
DIR_URL="$REPO/${PKGLETTER}/${PKGNAME}/"

curl -I $URL 2>/dev/null >/dev/null

if [ "0" -eq "$?" ]; then
    echo "Downloading $URL..."
    echo
    wget $URL
else
    echo "Failed, but see for yourself:"
    echo "  Repo: $REPO/"
    echo "  Pkg:  $DIR_URL"
    echo "  File: $URL"
    exit 2
fi

